WebAppMvcFissoloLorenzo/Controllers/RichiestaRimbosoFissoloLorenzoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAppMvcFissoloLorenzo.Data;
using WebAppMvcFissoloLorenzo.Models;

namespace WebAppMvcFissoloLorenzo.Controllers
{
    public class RichiestaRimbosoFissoloLorenzoController : Controller
    {
        private readonly WebAppMvcFissoloLorenzoContext _context;

        public RichiestaRimbosoFissoloLorenzoController(WebAppMvcFissoloLorenzoContext context)
        {
            _context = context;
        }

        // GET: RichiestaRimbosoFissoloLorenzo
        public async Task<IActionResult> Index(int Importo)
        {
            if (_context.RichiestaRimboso == null)
            {
                return Problem("Entity set 'MvcMovieContext.Movie'  is null.");
            }

            var richiesta = from m in _context.RichiestaRimboso
                         select m;

            if (Importo != 0)
            {
                richiesta = richiesta.Where(s => s.Importo < Importo);
            }

            return View(await richiesta.ToListAsync());
        }

        // GET: RichiestaRimbosoFissoloLorenzo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var richiestaRimboso = await _context.RichiestaRimboso
                .FirstOrDefaultAsync(m => m.Id == id);
            if (richiestaRimboso == null)
            {
                return NotFound();
            }

            return View(richiestaRimboso);
        }

        // GET: RichiestaRimbosoFissoloLorenzo/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RichiestaRimbosoFissoloLorenzo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Cognome,DataRichiesta,Telefono,email,PartitaIva,Richiesta,Importo")] RichiestaRimboso richiestaRimboso)
        {
            if (ModelState.IsValid)
            {
                _context.Add(richiestaRimboso);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(richiestaRimboso);
        }

        // GET: RichiestaRimbosoFissoloLorenzo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var richiestaRimboso = await _context.RichiestaRimboso.FindAsync(id);
            if (richiestaRimboso == null)
            {
                return NotFound();
            }
            return View(richiestaRimboso);
        }

        // POST: RichiestaRimbosoFissoloLorenzo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Cognome,DataRichiesta,Telefono,email,PartitaIva,Richiesta,Importo")] RichiestaRimboso richiestaRimboso)
        {
            if (id != richiestaRimboso.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(richiestaRimboso);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RichiestaRimbosoExists(richiestaRimboso.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(richiestaRimboso);
        }

        // GET: RichiestaRimbosoFissoloLorenzo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var richiestaRimboso = await _context.RichiestaRimboso
                .FirstOrDefaultAsync(m => m.Id == id);
            if (richiestaRimboso == null)
            {
                return NotFound();
            }

            return View(richiestaRimboso);
        }

        // POST: RichiestaRimbosoFissoloLorenzo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var richiestaRimboso = await _context.RichiestaRimboso.FindAsync(id);
            if (richiestaRimboso != null)
            {
                _context.RichiestaRimboso.Remove(richiestaRimboso);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RichiestaRimbosoExists(int id)
        {
            return _context.RichiestaRimboso.Any(e => e.Id == id);
        }
    }
}

WebAppMvcFissoloLorenzo/Views/RichiestaRimbosoFissoloLorenzo/Create.cshtml
@model WebAppMvcFissoloLorenzo.Models.RichiestaRimboso

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>RichiestaRimboso</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cognome" class="control-label"></label>
                <input asp-for="Cognome" class="form-control" />
                <span asp-validation-for="Cognome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataRichiesta" class="control-label"></label>
                <input asp-for="DataRichiesta" class="form-control" />
                <span asp-validation-for="DataRichiesta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PartitaIva" class="control-label"></label>
                <input asp-for="PartitaIva" class="form-control" />
                <span asp-validation-for="PartitaIva" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Richiesta" class="control-label"></label>
                <input asp-for="Richiesta" class="form-control" />
                <span asp-validation-for="Richiesta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Importo" class="control-label"></label>
                <input asp-for="Importo" class="form-control" />
                <span asp-validation-for="Importo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebAppMvcFissoloLorenzo/Views/RichiestaRimbosoFissoloLorenzo/Delete.cshtml
@model WebAppMvcFissoloLorenzo.Models.RichiestaRimboso

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RichiestaRimboso</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cognome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cognome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataRichiesta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataRichiesta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PartitaIva)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PartitaIva)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Richiesta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Richiesta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Importo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Importo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebAppMvcFissoloLorenzo/Views/RichiestaRimbosoFissoloLorenzo/Details.cshtml
@model WebAppMvcFissoloLorenzo.Models.RichiestaRimboso

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>RichiestaRimboso</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cognome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cognome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataRichiesta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataRichiesta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PartitaIva)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PartitaIva)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Richiesta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Richiesta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Importo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Importo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebAppMvcFissoloLorenzo/Views/RichiestaRimbosoFissoloLorenzo/Edit.cshtml
@model WebAppMvcFissoloLorenzo.Models.RichiestaRimboso

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>RichiestaRimboso</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cognome" class="control-label"></label>
                <input asp-for="Cognome" class="form-control" />
                <span asp-validation-for="Cognome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataRichiesta" class="control-label"></label>
                <input asp-for="DataRichiesta" class="form-control" />
                <span asp-validation-for="DataRichiesta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PartitaIva" class="control-label"></label>
                <input asp-for="PartitaIva" class="form-control" />
                <span asp-validation-for="PartitaIva" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Richiesta" class="control-label"></label>
                <input asp-for="Richiesta" class="form-control" />
                <span asp-validation-for="Richiesta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Importo" class="control-label"></label>
                <input asp-for="Importo" class="form-control" />
                <span asp-validation-for="Importo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebAppMvcFissoloLorenzo/Views/RichiestaRimbosoFissoloLorenzo/Index.cshtml
@model IEnumerable<WebAppMvcFissoloLorenzo.Models.RichiestaRimboso>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="RichiestaRimbosoFissoloLorenzo" asp-action="Index">
    <p>
        Importo: <input type="number" name="Importo" min="0" max="999" />
        <input type="submit" value="Filter"/>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cognome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataRichiesta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PartitaIva)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Richiesta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Importo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cognome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataRichiesta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PartitaIva)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Richiesta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Importo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>